language: python
python: 3.7
dist: xenial
sudo: true
before_install:
  - pip install --upgrade pip
  - pip install codecov
  - pip install poetry
install:
  - poetry install
script:
  - poetry run py.test
after_success:
  - codecov
before_deploy:
  - pip install --upgrade pip
  - poetry build
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
deploy:
  provider: script
  script: poetry publish
  on:
    tags: true
