on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Build

jobs:
  checking:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Dev dependencies
        run: |
          echo ${{github.ref}}
          pip install pytest black mypy pytest-asyncio pytest-cov pytest-black pytest-mypy
          pip install -e .

      - name: Run Tests
        run: python setup.py test
      - uses: codecov/codecov-action@v1
        with:
          file: ./reports/coverage.xml 
          flags: unittests 
          fail_ci_if_error: true 
          verbose: true 

  releasing:  
    name: Build Release
    runs-on: ubuntu-latest
    needs: checking
    if:  github.ref == 'refs/heads/master' 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Dev dependencies
        run: |
          pip install black
      - name: Release
        id: release
        uses: rymndhng/release-on-push-action@v0.14.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump_version_scheme: patch

      - name: Check Output Parameters
        run: echo "Got version ${{ steps.release.outputs.tag_name }}"
      - name: Print Version
        run: |
          sed -i '$ d' monads/__init__.py 
          echo "version='${{ steps.release.outputs.tag_name }}'" >>  monads/__init__.py   
          sed -i '9s/.*/    version="${{ steps.release.outputs.tag_name }}",/' setup.py 
          black setup.py 
          black monads/__init__.py    
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


          

